import 'package:custom_lint_builder/custom_lint_builder.dart';

import 'lints/bloc/bloc.dart';
import 'lints/common/common.dart';
import 'lints/fake_async/fake_async.dart';
import 'lints/flutter/flutter.dart';
import 'lints/provider/provider.dart';

PluginBase createPlugin() => _AwesomeLints();

class _AwesomeLints extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) => [
    ..._commonLintRules(configs),
    ...flutterLintRules,
    ...providerLintRules,
    ...blocLintRules,
    ...fakeAsyncLintRules,
  ];

  List<LintRule> _commonLintRules(CustomLintConfigs configs) {
    return [
      ArgumentsOrdering(),
      AvoidAccessingCollectionsByConstantIndex(),
      AvoidAccessingOtherClassesPrivateMembers(),
      AvoidAdjacentStrings(),
      AvoidAlwaysNullParameters(),
      AvoidAssigningToStaticField(),
      AvoidAssignmentsAsConditions(),
      AvoidAsyncCallInSyncFunction(),
      AvoidBarrelFiles(),
      AvoidBitwiseOperatorsWithBooleans(),
      AvoidBottomTypeInPatterns(),
      AvoidBottomTypeInRecords(),
      AvoidCascadeAfterIfNull(),
      AvoidCastingToExtensionType(),
      AvoidCollapsibleIf(),
      AvoidCollectionEqualityChecks(),
      AvoidCollectionMethodsWithUnrelatedTypes(),
      AvoidCollectionMutatingMethods(),
      AvoidCommentedOutCode(),
      AvoidComplexArithmeticExpressions(),
      AvoidComplexConditions(),
      AvoidComplexLoopConditions(),
      AvoidConditionsWithBooleanLiterals(),
      AvoidConstantAssertConditions(),
      AvoidConstantConditions(),
      AvoidConstantSwitches(),
      AvoidContinue(),
      AvoidContradictoryExpressions(),
      AvoidDeclaringCallMethod(),
      AvoidDefaultTostring(),
      AvoidDeprecatedUsage(),
      AvoidDoubleSlashImports(),
      AvoidDuplicateCascades(),
      AvoidDuplicateCollectionElements(),
      AvoidNonNullAssertion(),
      BinaryExpressionOperandOrder(),
      DisposeClassFields(),
      DoubleLiteralFormat(),
      NewlineBeforeCase(),
      NewlineBeforeConstructor(),
      NewlineBeforeMethod(),
      NewlineBeforeReturn(),
      NoBooleanLiteralCompare(),
      NoEmptyBlock(),
      NoEmptyString(),
      NoEqualArguments(),
      NoEqualConditions(),
      NoEqualNestedConditions(),
      NoEqualSwitchCase(),
      NoEqualSwitchExpressionCases(),
      NoEqualThenElse(),
      NoMagicNumber(),
      NoMagicString(),
      NoObjectDeclaration(),
      PreferAsyncAwait(),
      PreferContains(),
      PreferCorrectForLoopIncrement(),
      PreferCorrectJsonCasts(),
      PreferEarlyReturn(),
      PreferIterableOf(),
      PreferFirst(),
      PreferLast(),
      PreferNamedBooleanParameters(),
      PreferReturnAwait(),
      PreferSwitchExpression(configs: configs),
    ];
  }

  List<LintRule> flutterLintRules = [
    AvoidEmptySetstate(),
    AvoidLateContext(),
    AvoidMissingController(),
    AvoidMountedInSetstate(),
    AvoidSingleChildColumnOrRow(),
    AvoidStatelessWidgetInitializedFields(),
    AvoidUndisposedInstances(),
    AvoidUnnecessaryGestureDetector(),
    AvoidUnnecessaryOverridesInState(),
    AvoidUnnecessaryStatefulWidgets(),
    AvoidWrappingInPadding(),
    DisposeFields(),
    PassExistingFutureToFutureBuilder(),
    PassExistingStreamToStreamBuilder(),
    PreferActionButtonTooltip(),
    PreferAlignOverContainer(),
    PreferAsyncCallback(),
    PreferCenterOverAlign(),
    PreferComputeOverIsolateRun(),
    PreferConstrainedBoxOverContainer(),
    PreferContainer(),
    PreferDedicatedMediaQueryMethods(),
    PreferForLoopInChildren(),
    PreferPaddingOverContainer(),
    PreferSingleSetstate(),
    PreferSizedBoxSquare(),
    PreferSliverPrefix(),
    PreferSpacing(),
    PreferTextRich(),
    PreferVoidCallback(),
    PreferWidgetPrivateMembers(),
    ProperSuperCalls(),
  ];

  List<LintRule> providerLintRules = [
    AvoidInstantiatingInValueProvider(),
    AvoidReadInsideBuild(),
    AvoidWatchOutsideBuild(),
    DisposeProviders(),
    PreferImmutableSelectorValue(),
    PreferMultiProvider(),
    PreferNullableProviderTypes(),
    PreferProviderExtensions(),
  ];

  List<LintRule> blocLintRules = [
    AvoidBlocPublicFields(),
    AvoidBlocPublicMethods(),
    AvoidCubits(),
    AvoidDuplicateBlocEventHandlers(),
    AvoidEmptyBuildWhen(),
    AvoidExistingInstancesInBlocProvider(),
    AvoidInstantiatingInBlocValueProvider(),
    AvoidPassingBlocToBloc(),
    AvoidPassingBuildContextToBlocs(),
    AvoidReturningValueFromCubitMethods(),
    CheckIsNotClosedAfterAsyncGap(),
    EmitNewBlocStateInstances(),
    HandleBlocEventSubclasses(),
    PreferBlocEventSuffix(),
    PreferBlocExtensions(),
    PreferBlocStateSuffix(),
    PreferCorrectBlocProvider(),
    PreferImmutableBlocEvents(),
    PreferImmutableBlocState(),
    PreferMultiBlocProvider(),
    PreferSealedBlocEvents(),
    PreferSealedBlocState(),
  ];

  List<LintRule> fakeAsyncLintRules = [AvoidAsyncCallbackInFakeAsync()];
}
